-- INFO 210: Database Management Systems Final Project Summer 2019
-- Drexel University College of Computing and Informatics
 
--Johnson, A. E., Pollard, T. J., Shen, L., Lehman, L. H., Feng, M., Ghassemi, M., . . . Mark, R. G.
-- (2016, May 24). MIMIC-III, a freely accessible critical care database. Retrieved July 1,
-- 2019, from https://www.nature.com/articles/sdata201635/


CREATE TABLE PATIENT(
    ROW_ID INT,
    PATIENT_ID INT PRIMARY KEY NOT NULL,
    GENDER VARCHAR2(5),
    PATIENT_DOB TIMESTAMP,
    PATIENT_DOD TIMESTAMP,
    DOD_SSN TIMESTAMP,
    DOD_HOSPITAL TIMESTAMP,
    EXPIRE_FLAG VARCHAR2(5));

INSERT INTO PATIENT VALUES(1, 1, 'MALE', '01/19/2019', '04/16/2019', 120-50-0213, '04/16/2019', TRUE);
INSERT INTO PATIENT VALUES(2, 2, 'FEMALE', '08/25/1999', NULL, NULL, NULL, NULL, FALSE);
INSERT INTO PATIENT VALUES(3, 3, 'FEMALE', '03/03/1982', NULL, NULL, NULL, NULL, FALSE);


CREATE TABLE ADMISSIONS(
    ROW_ID INT,
    HOSP_ADM_ID INT PRIMARY KEY NOT NULL,
    PATIENT_ID INT,
    ADM_TIME TIMESTAMP,
    DISCH_TIME TIMESTAMP,
    DEATH_TIME TIMESTAMP,
    ADM_TYPE VARCHAR(50),
    ADM_LOC VARCHAR(50), 
    DISCH_LOC VARCHAR(50),
    INSURANCE VARCHAR(255),
    LANGUAGE_TYPE VARCHAR(10),
    RELIGION VARCHAR(50),
    MARITAL_STATUS VARCHAR(50),
    ETHNICITY VARCHAR(200),
    ED_REG_TIME TIMESTAMP,
    ED_OUT_TIME TIMESTAMP,
    DIAGNOSIS VARCHAR(300),
    HOSPITAL_EXPIRE_FLAG BOOLEAN,
    HAS_CHART_EVENTS_DATA BOOLEAN,
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID));


INSERT INTO ADMISSIONS VALUES(1, 1, 1, '04/15/2019 2:00 PM EST', NULL, '04/16/2019 1:45 AM EST', 'NEWBORN', '** INFO NOT AVAILABLE **', NULL, NULL, NULL, NULL, NULL, 'WHITE', '04/16/2019 1:30 AM EST', '04/16/2019 1:50 AM EST', 'Hypertensive heart and chronic kidney disease.', TRUE, TRUE);
INSERT INTO ADMISSIONS VALUES(2, 2, 2, '04/17/2019 4:35 PM EST', '04/18/2019 10:45 AM EST', NULL, 'URGENT', 'TRSF WITHIN THIS FACILITY', 'EMERGENCY', 'MEDICAID', 'BANGLADESHI', 'HINDU', 'SINGLE', 'BANGLADESHI', '04/17/2019 4:35 PM EST', '04/18/2019 8:00 AM EST', 'Chronic obstructive pulmonary disease, unspecified.', FALSE, TRUE);
INSERT INTO ADMISSIONS VALUES(3, 3, 3, '04/17/2019 7:35 AM EST', '04/17/2019 4:15 PM EST', NULL, 'EMERGENCY', 'EMERGENCY ROOM ADMIT', 'CRITICAL CARE UNIT', 'MEDICARE', 'ENGLISH', 'CATHOLIC', 'MARRIED', 'WHITE', '04/17/2019 10:27 AM EST', '04/17/2019 4:55 PM EST', 'Varicose veins of other sites. A disorder characterized by bleeding from esophageal varices', FALSE, TRUE);

CREATE TABLE LAB_ITEMS (
    ROW_ID INT,
    LAB_ITEM_ID INT PRIMARY KEY,
    LABEL VARCHAR(100),
    FLUID VARCHAR(100),
    CATEGORY VARCHAR(100),
    LOINC_CODE VARCHAR(100));

INSERT INTO LAB_ITEMS VALUES(1,1,'POTASSIUM, SERUM', 'BLOOD', 'ABG', '2823-3');
INSERT INTO LAB_ITEMS VALUES(2,2,'Hemoglobin [Mass/volume] in Blood', 'BLOOD', 'HEM/BC', '718-7');
INSERT INTO LAB_ITEMS VALUES(3,3, 'Iron deficiency anemia secondary to blood loss (chronic)', NULL, '285-1');


CREATE TABLE LAB_EVENTS (
    ROW_ID INT,
    PATIENT_ID INT,
    HOSP_ADM_ID INT,
    LAB_ITEM_ID INT,
    CHART_TIME TIMESTAMP, 
    MEASURED_VALUE VARCHAR(200),
    VALUE_UOM VARCHAR(20),
    VALUE_NUM DECIMAL,
    FLAG VARCHAR(20),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
    FOREIGN KEY (HOSP_ADM_ID) REFERENCES ADMISSIONS(HOSP_ADM_ID),
    FOREIGN KEY (LAB_ITEM_ID) REFERENCES LAB_ITEMS(LAB_ITEM_ID));

INSERT INTO LAB_EVENTS VALUES(1,1,1,1, '04/16/2019', '1.2-2.5', 'mmol/L', '1.2-2.5', 'ABNORMAL');
INSERT INTO LAB_EVENTS VALUES(2,2,2,2, '04/17/2019', '13.2-17.1', 'g/dL', '13.2-17.1', 'NORMAL');
INSERT INTO LAB_EVENTS VALUES(3,3,3,3, '04/17/2019', '27-164', 'mcg/dL', '27-164', 'ABNORMAL');


CREATE TABLE CPT_EVENTS (
    ROW_ID INT,
    PATIENT_ID INT,
    HOSP_ADM_ID INT,
    COST_CENTER VARCHAR(10),
    CHART_DATE  TIMESTAMP,
    CPT_CODE VARCHAR(10),
    CPT_NUM INT,
    CPT_SUFFIX VARCHAR(5),
    TICKET_ID_SEQ INT,
    SECTION_HEADER VARCHAR(50),
    SUBSECTION_HEADER VARCHAR(300),
    CPT_CODE_DESCRIPTION VARCHAR(200),
    FOREIGN KEY (HOSP_ADM_ID) REFERENCES ADMISSIONS(HOSP_ADM_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID));

INSERT INTO CPT_EVENTS VALUES(1,1,1, 'ICU', '04/15/2019 2:00 PM EST', 'Potassium; serum, plasma or whole blood', '84132', 'Potassium; serum, plasma or whole blood', 1, 'Pathology and laboratory', 'anatomical pathology', NULL);
INSERT INTO CPT_EVENTS VALUES(2,2,2, 'ICU', '04/17/2019 4:35 PM EST', 'Hemoglobin [Mass/volume] in Blood', '85018', 'Hemoglobin [Mass/volume] in Blood', 1, 'Pathology and laboratory', 'anatomical pathology', NULL );
INSERT INTO CPT_EVENTS VALUES(2,2,2, 'ICU', '04/17/2019 7:35 AM EST', 'Iron deficiency anemia secondary to blood loss (chronic)', '83540', 'Iron deficiency anemia secondary to blood loss (chronic)', 1 ,'Pathology and laboratory', 'anatomical pathology', NULL);

